### ISSUE TITLE
Overriding default options

### ISSUE THREAD

**Issue by aklkv** [davewasmer/ember-cli-favicon#4]
Hi, I am trying to override default options, but I am not sure if I am doing it wrong or my setting do not get passed. Here is my ember-cli-build:

``` javascript
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
   fingerprint: {
     exclude: ['apple-touch-icon', 'favicon', 'mstile']
   },
   favicon: {
     source: '/public/assets/img/favicon.png' , // Source image(s). `string`, `buffer` or array of `{ size: filepath }`
     configuration:  {
         appName: null,                  // Your application's name. `string`
         appDescription: null,           // Your application's description. `string`
         developerName: null,            // Your (or your developer's) name. `string`
         developerURL: null,             // Your (or your developer's) URL. `string`
         background: "#fff",             // Background colour for flattened icons. `string`
         path: "/",                      // Path for overriding default icons path. `string`
         url: "/",                       // Absolute URL for OpenGraph image. `string`
         display: "standalone",          // Android display: "browser" or "standalone". `string`
         orientation: "portrait",        // Android orientation: "portrait" or "landscape". `string`
         version: "1.0",                 // Your application's version number. `number`
         logging: true,                  // Print logs to console? `boolean`
         online: false,                  // Use RealFaviconGenerator to create favicons? `boolean`
         icons: {
             android: true,              // Create Android homescreen icon. `boolean`
             appleIcon: true,            // Create Apple touch icons. `boolean`
             appleStartup: true,         // Create Apple startup images. `boolean`
             coast: true,                // Create Opera Coast icon. `boolean`
             favicons: true,             // Create regular favicons. `boolean`
             firefox: true,              // Create Firefox OS icons. `boolean`
             opengraph: true,            // Create Facebook OpenGraph. `boolean`
             windows: true,              // Create Windows 8 tiles. `boolean`
             yandex: true                // Create Yandex browser icon. `boolean`
         }
      }
    }
  });

  return app.toTree();
};
```

Thank you

**Comment by jrdn91** [comment]
same here, can you show an example in the readme how you intend configuration to be passed in?

**Comment by davewasmer** [comment]
The configuration you are passing in is for the new version of the underlying favicons module, which this addon hasn't been upgraded to yet. That is in the works, but in the meantime, try using the config as described here: https://github.com/haydenbleasel/favicons/tree/dbd790f152bab478cf9049bb22cb5c4f39d3650d

**Comment by aklkv** [comment]
I have updated my configuration but it it doesn't make it's way to plugin:

``` javascript
favicon: {
      // files: {
      //   src: 'public/assets/img/',
      // },
      icons: {
        android: false,
        appleIcon: false,
        appleStartup: false,
        coast: false,
        favicons: false,
        firefox: false,
        opengraph: false,
        windows: false,
        yandex: false
      },
      settings: {
        appName: 'Semios',
        appDescription: null,
        developer: 'SemiosBIO Tech',
        developerURL: 'http://semios.com',
        version: 1.0,
        background: '#fff',
        // url: 'http://dev.semios.com',
        silhouette: false, // Turn the logo into a white silhouette for Windows 8. `boolean`
        logging: true // Print logs to console? `boolean`
      },
      favicon_generation: {
        favicon_design: {
          ios: {
            margin: 6
          }
        },
        settings: {
          compression: 3
        }
      }
    }
```

```
Building.Source file for android favicon (public/favicon.png) does not exist!
Source file for appleIcon favicon (public/favicon.png) does not exist!
Source file for appleStartup favicon (public/favicon.png) does not exist!
Source file for coast favicon (public/favicon.png) does not exist!
Source file for firefox favicon (public/favicon.png) does not exist!
Source file for opengraph favicon (public/favicon.png) does not exist!
Source file for windows favicon (public/favicon.png) does not exist!
Source file for yandex favicon (public/favicon.png) does not exist!
Source file for favicons favicon (public/favicon.png) does not exist!
Build failed.
Missing favicon source files!
Error: Missing favicon source files!
  at Favicons.updateCache (/Users/uni_mac/Desktop/SemiosBIO/brae-ember/node_modules/broccoli-favicon/index.js:113:24)
  at /Users/uni_mac/Desktop/SemiosBIO/brae-ember/node_modules/broccoli-favicon/node_modules/broccoli-caching-writer/index.js:96:34
  at lib$rsvp$$internal$$tryCatch (/Users/uni_mac/Desktop/SemiosBIO/brae-ember/node_modules/rsvp/dist/rsvp.js:493:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/uni_mac/Desktop/SemiosBIO/brae-ember/node_modules/rsvp/dist/rsvp.js:505:17)
  at lib$rsvp$$internal$$publish (/Users/uni_mac/Desktop/SemiosBIO/brae-ember/node_modules/rsvp/dist/rsvp.js:476:11)
  at lib$rsvp$asap$$flush (/Users/uni_mac/Desktop/SemiosBIO/brae-ember/node_modules/rsvp/dist/rsvp.js:1198:9)
  at doNTCallback0 (node.js:407:9)
  at process._tickCallback (node.js:336:13)

```

**Comment by davewasmer** [comment]
@aklkv the new version (1.0.0-beta.2) should solve this issue. It uses the latest favicons module under the hood, so your configuration should look like this now:

``` js
new EmberApp({
  favicons: {
    config: {
      // this object is passed directly to favicons
    }
  }
});
```

Let me know if you are still having any other issues
