### ISSUE TITLE
Build error with `ember build`

### ISSUE THREAD

**Issue by melv-n** [davewasmer/ember-cli-favicon#66]
Potential duplicate of #62 
```
☁  bazaar [master] ⚡ ember build --environment production
DEPRECATION: Addon files were detected in `/Users/melvin/Projects/bazaar/node_modules/ember-cli-foundation-6-sass/addon`, but no JavaScript preprocessors were found for `ember-cli-foundation-6-sass`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-cli-foundation-6-sass`'s `package.json`.
DEPRECATION: Addon files were detected in `/Users/melvin/Projects/bazaar/node_modules/ember-cli-foundation-6-sass/addon`, but no JavaScript preprocessors were found for `ember-cli-foundation-6-sass`. Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-cli-foundation-6-sass`'s `package.json`.
cleaning up...
Build failed.
The Broccoli Plugin: [CachingWriter] failed with:
Error: ENOENT: no such file or directory, stat '/Users/melvin/Projects/bazaar/tmp/caching_writer-input_base_path-ckcD2taa.tmp/0/favicon.png'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at CachingWriter.keyForFile (/Users/melvin/Projects/bazaar/node_modules/broccoli-caching-writer/index.js:87:20)
    at Array.map (native)
    at CachingWriter._conditionalBuild (/Users/melvin/Projects/bazaar/node_modules/broccoli-caching-writer/index.js:109:65)
    at /Users/melvin/Projects/bazaar/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at tryCatch (/Users/melvin/Projects/bazaar/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/melvin/Projects/bazaar/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/Users/melvin/Projects/bazaar/node_modules/rsvp/dist/rsvp.js:522:7)
    at flush (/Users/melvin/Projects/bazaar/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)


The broccoli plugin was instantiated at:
    at CachingWriter.Plugin (/Users/melvin/Projects/bazaar/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at new CachingWriter (/Users/melvin/Projects/bazaar/node_modules/broccoli-caching-writer/index.js:18:10)
    at CachingWriter.Favicons (/Users/melvin/Projects/bazaar/node_modules/broccoli-favicon/index.js:45:10)
    at Class.postprocessTree (/Users/melvin/Projects/bazaar/node_modules/ember-cli-favicon/index.js:24:22)
    at projectOrAddon.addons.reduce (/Users/melvin/Projects/bazaar/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (native)
    at addonProcessTree (/Users/melvin/Projects/bazaar/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/Users/melvin/Projects/bazaar/node_modules/ember-cli/lib/broccoli/ember-app.js:564:10)
    at EmberApp.toTree (/Users/melvin/Projects/bazaar/node_modules/ember-cli/lib/broccoli/ember-app.js:1695:15)
    at module.exports (/Users/melvin/Projects/bazaar/ember-cli-build.js:45:14)
    at FastBootBuild.toTree (/Users/melvin/Projects/bazaar/node_modules/ember-cli-fastboot/lib/broccoli/fastboot-build.js:73:41)
    at Class.buildFastBootTree (/Users/melvin/Projects/bazaar/node_modules/ember-cli-fastboot/index.js:136:26)
    at Class.postprocessTree (/Users/melvin/Projects/bazaar/node_modules/ember-cli-fastboot/index.js:118:31)
    at projectOrAddon.addons.reduce (/Users/melvin/Projects/bazaar/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (native)
    at addonProcessTree (/Users/melvin/Projects/bazaar/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/Users/melvin/Projects/bazaar/node_modules/ember-cli/lib/broccoli/ember-app.js:564:10)
    at EmberApp.toTree (/Users/melvin/Projects/bazaar/node_modules/ember-cli/lib/broccoli/ember-app.js:1695:15)
    at module.exports (/Users/melvin/Projects/bazaar/ember-cli-build.js:45:14)
    at Builder.setupBroccoliBuilder (/Users/melvin/Projects/bazaar/node_modules/ember-cli/lib/models/builder.js:54:19)
    at new Builder (/Users/melvin/Projects/bazaar/node_modules/ember-cli/lib/models/builder.js:33:10)
    at BuildTask.run (/Users/melvin/Projects/bazaar/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Win.checkIfSymlinksNeedToBeEnabled.then (/Users/melvin/Projects/bazaar/node_modules/ember-cli/lib/commands/build.js:32:29)
    at tryCatch (/Users/melvin/Projects/bazaar/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/melvin/Projects/bazaar/node_modules/rsvp/dist/rsvp.js:554:13)
    at /Users/melvin/Projects/bazaar/node_modules/rsvp/dist/rsvp.js:629:16
    at flush (/Users/melvin/Projects/bazaar/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

*Update* Adding the workaround proposed by @fiddler worked:
```
  var app = new EmberApp(defaults, {
    // Add options here
    fingerprint: {
      exclude: ['apple-touch-icon', 'favicon', 'mstile']
    }
  });
```
https://github.com/davewasmer/ember-cli-favicon/issues/62#issuecomment-281573340

**Comment by Duder-onomy** [comment]
This started happening for me when I implemented fastboot.  Workaround mentioned above fixed it.

**Comment by davewasmer** [comment]
This should be fixed in the latest release (the addon should automatically add those exclusions to the fingerprinting options). Feel free to drop a note if not, and I'll reopen.
